"""Persistence ports for the applications module."""

from __future__ import annotations

from typing import Protocol

from .entities import Application


class ApplicationRepository(Protocol):
    def add(self, application: Application) -> Application: ...
    def get(self, application_id: str) -> Application | None: ...
    def get_by_slug(self, slug: str) -> Application | None: ...
    def get_by_name(self, name: str) -> Application | None: ...
    def list(self) -> list[Application]: ...
    def update(self, application: Application) -> Application: ...
    def delete(self, application_id: str) -> None: ...


