"""Persistence contract for schedules."""

from __future__ import annotations

from typing import Protocol

from .schedules import Schedule


class ScheduleRepository(Protocol):
    def add(self, schedule: Schedule) -> Schedule: ...
    def get(self, schedule_id: str) -> Schedule | None: ...
    def get_by_name(self, name: str) -> Schedule | None: ...
    def list(self, *, status: str | None = ...) -> list[Schedule]: ...
    def due(self, limit: int = ...) -> list[Schedule]: ...
    def update(self, schedule: Schedule) -> Schedule: ...
    def delete(self, schedule_id: str) -> None: ...
