"""Persistence ports for the analysis module."""

from __future__ import annotations

from typing import Protocol

from .entities import Dashboard, Visualization


class VisualizationRepository(Protocol):
    def add(self, visualization: Visualization) -> Visualization: ...
    def get(self, visualization_id: str) -> Visualization | None: ...
    def list(self) -> list[Visualization]: ...
    def update(self, visualization: Visualization) -> Visualization: ...
    def delete(self, visualization_id: str) -> None: ...


class DashboardRepository(Protocol):
    def add(self, dashboard: Dashboard) -> Dashboard: ...
    def get(self, dashboard_id: str) -> Dashboard | None: ...
    def get_by_name(self, name: str) -> Dashboard | None: ...
    def list(self) -> list[Dashboard]: ...
    def update(self, dashboard: Dashboard) -> Dashboard: ...
    def delete(self, dashboard_id: str) -> None: ...
