"""Persistence contract for reports."""

from __future__ import annotations

from typing import Protocol

from .entities import Report


class ReportRepository(Protocol):
    def add(self, report: Report) -> Report: ...
    def get(self, report_id: str) -> Report | None: ...
    def get_by_name(self, name: str) -> Report | None: ...
    def list(self) -> list[Report]: ...
    def update(self, report: Report) -> Report: ...
    def delete(self, report_id: str) -> None: ...
