"""Persistence ports for the model module.

The application layer is typed against these Protocols, never against the
SQLAlchemy repositories that implement them.
"""

from __future__ import annotations

from typing import Protocol

from .entities import ModelDefinition, ModelVersion


class ModelRepository(Protocol):
    def add(self, model: ModelDefinition) -> ModelDefinition: ...
    def get(self, model_id: str) -> ModelDefinition | None: ...
    def get_by_slug(self, slug: str) -> ModelDefinition | None: ...
    def get_by_name(self, name: str) -> ModelDefinition | None: ...
    def list(
        self, *, model_type: str | None = ..., provider: str | None = ...
    ) -> list[ModelDefinition]: ...
    def update(self, model: ModelDefinition) -> ModelDefinition: ...
    def delete(self, model_id: str) -> None: ...

    def add_version(self, version: ModelVersion) -> ModelVersion: ...
    def get_version(self, version_id: str) -> ModelVersion | None: ...
    def list_versions(self, model_id: str) -> list[ModelVersion]: ...
    def next_version_number(self, model_id: str) -> int: ...
