"""model scope

Revision ID: 2f97bd4eacab
Revises: fcd30aaa8f03
Create Date: 2026-08-21 18:10:21.758569
"""

from __future__ import annotations

from collections.abc import Sequence

import json

import sqlalchemy as sa
from alembic import op


revision: str = '2f97bd4eacab'
down_revision: str | None = 'fcd30aaa8f03'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('scope', sa.String(length=16), server_default='library', nullable=False))
    op.create_index(op.f('ix_models_scope'), 'models', ['scope'], unique=False)
    # ### end Alembic commands ###

    #  Backfill from the pipelines themselves rather than from a naming
    #  convention: a model is step-scoped exactly when a pipeline step points
    #  at it, and that is recorded in `pipelines.steps`.
    connection = op.get_bind()
    owned: set[str] = set()
    for (steps,) in connection.execute(sa.text("SELECT steps FROM pipelines")):
        parsed = json.loads(steps) if isinstance(steps, str) else (steps or [])
        for step in parsed:
            if isinstance(step, dict) and step.get("model_id"):
                owned.add(step["model_id"])

    if owned:
        connection.execute(
            sa.text("UPDATE models SET scope = 'step' WHERE id IN :ids").bindparams(
                sa.bindparam("ids", value=tuple(owned), expanding=True)
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_scope'), table_name='models')
    op.drop_column('models', 'scope')
    # ### end Alembic commands ###
