"""model status

Revision ID: 565db84248eb
Revises: f563c8d4e807
Create Date: 2026-08-22 06:37:43.709913
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '565db84248eb'
down_revision: str | None = 'f563c8d4e807'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('models', sa.Column('status', sa.String(length=16), server_default='active', nullable=False))
    op.create_index(op.f('ix_models_status'), 'models', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_models_status'), table_name='models')
    op.drop_column('models', 'status')
    # ### end Alembic commands ###
